# Generated by Django 3.2.9 on 2021-11-22 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reys_raqami', models.CharField(max_length=100)),
                ('reys_nomi', models.CharField(max_length=100)),
                ('qaysi_shaxardan', models.CharField(max_length=100)),
                ('qaysi_shaharga', models.CharField(max_length=100)),
                ('uchish_sanasi', models.DateField()),
                ('uchish_vaqti', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Yolovchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=100)),
                ('familiyasi', models.CharField(max_length=100)),
                ('otasi_ismi', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reys.reys')),
                ('yolovchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reys.yolovchi')),
            ],
        ),
    ]
