# Generated by Django 3.2.9 on 2021-11-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reys',
            name='rasmi',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
